num1 = int(input("Enter first number:"))
num2 = int(input("Enter second number:"))
Sum = int(num1 + num2)
Difference = int(num1 - num2)
Product = int(num1*num2)
Quotient = float(num1/num2)
print(f"Sum:{Sum}")
print(f"Difference:{Difference}")
print(f"Product:{Product}")
print(f"Quotient:%.2f"%Quotient)